# Generated by Django 2.2.8 on 2019-12-16 08:13

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvup',
            name='cv',
            field=models.FileField(default='CV/data//default.pdf', upload_to='CV/data/', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.pdf', '.pdf'], allowed_types=['application/pdf'])]),
        ),
    ]
