# Generated by Django 2.2.8 on 2019-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191216_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvup',
            name='cv',
            field=models.FileField(default='CV/data//default.pdf', upload_to='CV/data/'),
        ),
    ]
