# Generated by Django 2.2.8 on 2019-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191219_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvup',
            name='cv',
            field=models.FileField(default='default.pdf', upload_to='CV/data/'),
        ),
    ]
