# Generated by Django 2.2.8 on 2019-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191219_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvup',
            old_name='cv',
            new_name='file',
        ),
    ]
