# Generated by Django 2.2.8 on 2019-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191219_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='000', max_length=15),
            preserve_default=False,
        ),
    ]
