# Generated by Django 2.2.8 on 2019-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(default="{'skill':None}", max_length=1000),
            preserve_default=False,
        ),
    ]
